env:
  global:
    - CC_TEST_REPORTER_ID=0bdc7cf0256747d51c968c18502f27c34c50afd1a3dfd136ddc6e6ffc51b8c1d
addons:
  postgresql: 9.6
  firefox: '65.0'
  apt:
    update: true
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.travis config/application.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
dist: trusty
language: ruby
rvm:
  - 2.5.3
install:
  - bundle install
  - nvm install node
  - node -v
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails webpacker:compile
  - yarn lint
  - bundle exec rubocop
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  yarn: true
