# Base Image
FROM ruby:3.2.2

# Encoding
# C.UTF8 locale supports Computer English language
ENV LANG C.UTF-8

# Default user and group id. This is important to avoid permission errors.
#
# All Linux users have a user ID and a group ID and a unique numerical
# identification number called a userid (UID) and a groupid (GID) respectively.
# Groups can be assigned to logically tie users together for a common security,
# privilege and access purpose. It is the foundation of Linux security and
# access.
ARG USER_ID=1000
ARG GROUP_ID=1000

# -q, --quiet
#    Quiet. Produces output suitable for logging, omitting progress indicators.
#    More q's will produce more quiet up to a maximum of two. You can also use
#    -q=# to set the quiet level, overriding the configuration file. Note that
#    quiet level 2 implies -y, you should never use -qq without a no-action
#    modifier such as -d, --print-uris or -s as APT may decided to do something
#    you did not expect.
#
#    build-essential is a package which contains references to numerous
#    packages needed for building software in general, it contais g++, gcc,
#    make tool between others package
#
#    curl is used in command lines or scripts to transfer data
#
#    libpq-dev are header files and static library for compiling C programs to
#    link with the libpq library in order to communicate with a PostgreSQL
#    database backend.
#
#    libxml2-dev Development files for the GNOME XML library
#
#    libxslt1-dev XSLT is an XML language for defining transformations of XML
#    files from XML to some other arbitrary format, such as XML, HTML, plain
#    text, etc.
#
#    imagemagick is a free and open-source software suite for displaying,
#    creating, converting, modifying, and editing raster image.
#
#    git
#    Git is a distributed version-control system for tracking changes in
#    source code during software development.
#
#    sudo
#    sudo is a program for Unix-like computer operating systems that
#    allows users to run programs with the security privileges of another user,
#    by default the superuser.
#
#    ssh
#    Secure Shell is a cryptographic network protocol for operating network
#    services securely over an unsecured network.
#
#    procps
#    This package provides command line and full screen utilities for b
#    procfs, a "pseudo" file system dynamically generated by the kernel to
#    provide information about the status of entries in its process table
#    (such as whether the process is running, stopped, or a "zombie").
#    .
#    It contains free, kill, pkill, pgrep, pmap, ps, pwdx, skill, slabtop,
#    snice, sysctl, tload, top, uptime, vmstat, w, and watch.
RUN apt-get update -qq && \
  apt-get install -y curl         \
  libpq-dev    \
  libxml2-dev  \
  libxslt1-dev \
  imagemagick  \
  git          \
  sudo         \
  ssh          \
  rsync        \
  procps       \
  cron         \
  vim

# --------------------------
# INSTALL LAST VERSION OF postgresql-client
# --------------------------
RUN apt-get install -y lsb-release
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >>  /etc/apt/sources.list.d/pgdg.list     &&  \
  sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
  apt-get install -y wget ca-certificates && \
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  apt-get update -qq && \
  apt-get install -y postgresql-client

# Define environment variables
ENV APP_NAME sgtcc
ENV APP /var/www/${APP_NAME}
ENV BUNDLE_PATH /bundle/vendor

RUN mkdir -p $APP \
  && mkdir -p $BUNDLE_PATH

# Set working directory
WORKDIR $APP

# Install bundler and rails
RUN gem install bundler -v 2.6.8 \
  && gem install rails -v 7.2.2.1
