x-app: &app
  build:
    context: .
    dockerfile: Dockerfile.development
  volumes:
    - .:/var/www/sgtcc
    - bundle_path:/bundle
  tmpfs:
    - /tmp
  depends_on:
    - db
  networks:
    - app-network
  stdin_open: true
  tty: true

services:
  web:
    <<: *app
    command: >
      bash -c "
        sudo rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
        " # Removing server.pid is technically a cleanup script
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development

  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app-network

  tests:
    <<: *app
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@db
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      TEST_APP_HOST: tests
      # https://github.com/DatabaseCleaner/database_cleaner#safeguards
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
    shm_size: "2gb" #set shared memory
    depends_on:
      - db
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - ./test/samples:/var/www/sgtcc/test/samples
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network

volumes:
  pgdata:
    driver: local
  bundle_path:

networks:
  app-network:
    driver: bridge
