#!/usr/bin/env bash
# https://github.com/nickjj/docker-rails-example/blob/main/run

# The set -o errexit (or the equivalent set -e) instruction in shell script
# is used to enable the error handling option, also known as "exit-on-error" or "errexit mode."
# When this option is enabled, the script will automatically terminate its execution
# (or exit with an error code) if any command in the script returns a non-zero exit code (indicating an error).
# This helps make scripts more robust and secure by ensuring that any unexpected failure
# in a command immediately halts the script's execution.
set -o errexit

# The set -o pipefail option in shell script is used to set the exit status of a pipeline to the value of the last (rightmost)
# command that exits with a non-zero status, or to zero if all commands in the pipeline exit successfully.
#
# Using set -o pipefail can be beneficial when you need to ensure that the entire pipeline
# behaves as expected, and you want to detect and handle failures accurately throughout the pipeline.
set -o pipefail

# Define a variable with default value as exec
# The - is a convention to default values.
# To override
# DC="run --rm" ./run
DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker compose
# commands that enable it by default, such as exec and run.
#
# This statement tests whether the script is being executed in a terminal or if
# the output has been redirected to some other place (e.g., a file).
# It can be used to control the script's behavior based on the context in which it is being executed.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker compose "${DC}" ${TTY} "${@}"
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Docker functions.
# -----------------------------------------------------------------------------

function dc {
  docker compose "${@}"
}

function ps {
  dc ps "${@}"
}

function up {
  dc up "${@}"
}

function dcr {
  dc run --rm "${@}"
}

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Rails commands.
# -----------------------------------------------------------------------------
# rails assets:clean       # Remove old compiled assets
# rails assets:clobber     # Remove compiled assets

function rails {
  # Run any Rails commands
  cmd rails "${@}"
}

function bundle {
  # Run any Rails commands
  cmd bundle "${@}"
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Linters commands.
# -----------------------------------------------------------------------------

# Run eslint using a custom container
# Commands:
# docker compose run --rm eslint
# docker compose run --rm eslint controllers/markdown_viewer_controller.js
# docker compose run --rm eslint --fix
# docker compose run --rm eslint --fix controllers/markdown_viewer_controller.js
function eslint {
   FILES_PATH="${@:-.}"
   docker compose run --rm eslint ${FILES_PATH}
 }

function brakeman {
 cmd bundle exec brakeman --ignore-config config/brakeman.ignore "${@}"
}

function rubocop {
  cmd bundle exec rubocop --parallel "${@}"
}

function linters {
  rubocop
  brakeman
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Rails tests commands.
# -----------------------------------------------------------------------------
function rspec {
  _dc tests bundle exec rspec "${@}"
}

# Access remmina VNC: 
# url: localhost:5900 
# password: secret 
function rspec:browser {
  docker compose exec -e LAUNCH_BROWSER=TRUE tests bundle exec rspec "${@}"
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Git commands
# -----------------------------------------------------------------------------
function git:clean:branchs {
  git branch | grep -v '\*\|master\|main\|develop\|production' | xargs -n 1 git branch -D
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Sheel commands.
# -----------------------------------------------------------------------------

function shell {
  # Start a shell session in the web container
  cmd bash "${@}"
}

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Database commands.
# -----------------------------------------------------------------------------
function psql {
  # Connect to PostgreSQL with psql
  # shellcheck disable=SC1091
  _dc db psql -U postgres "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
