name: Tests

on:
  workflow_call:
    secrets:
      MAILER_USERNAME:
        required: true
      MAILER_PASSWORD:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.2
    services:
      db:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup application.yml
        run: |
          echo "
              database: &database
                db.username: postgres
                db.password: postgres
                db.host: postgres://postgres:@db

              mailer: &mailer
                mailer.from: 'tcc-tsi-gp@utfpr.edu.br'
                mailer.host: localhost
                mailer.host.port: '3000'
                mailer.smtp: 'smtp.mailtrap.io'
                mailer.smtp.port: '2525'
                mailer.smtp.domain: 'smtp.mailtrap.io'
                mailer.smtp.username: '{{ secrets.MAILER_USERNAME }}'
                mailer.smtp.password: '${{ secrets.MAILER_PASSWORD }}'
                mailer.smtp.authentication: 'cram_md5'
                mailer.exception.prefix: '[SGTCC]'
                mailer.exception.sender: 'SGTCC <tcc-tsi-gp@utfpr.edu.br>'
                mailer.exception.recipient: 'tcc-tsi-gp@utfpr.edu.br'

              ldap: &ldap
                ldap.on: 'false'

              test:
                <<: *database
                <<: *mailer
                <<: *ldap
          " > config/application.yml

      - name: Install libpq-dev for postgres
        run: apt-get -yqq install libpq-dev

      - name: Cache bundle gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundle gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          RAILS_ENV: test
          COVERAGE: true
        run: |
          bundle exec rails db:prepare
          bundle exec rails rspec spec/models
