name: CI
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "@MarczalTSIGP/188/setup-ci"

jobs:
  #tests:
  #  uses: ./.github/workflows/_tests.yml
  #  secrets:
  #    MAIL_USERNAME: ${{ secrets.MAILER_USERNAME }}
  #    MAIL_PASSWORD: ${{ secrets.MAILER_PASSWORD }}

  code_quality:
    uses: ./.github/workflows/_linters.yml
    secrets:
      MAIL_USERNAME: ${{ secrets.MAILER_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
